Repository boostcampaitech4lv23recsys1/level3_productserving-level3-recsys-03, pull requests merged in 2023-01, with the labels that each got.

#13 ✨ feat: Add erasing all button (#12)
  frontend/.firebase/hosting.YnVpbGQ.cache
  frontend/src/Auth.tsx
  frontend/src/screens/FullTestSolve.tsx
  frontend/src/screens/RandomSolve.tsx
  frontend/src/screens/SpecificSolve.tsx
Labels: enhancement

#16 📝 docs: Add PR template & Issue template (#8)
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#19 📝 docs: Add .gif to README.md
  README.md
Labels: documentation

#22 ✨ feat: Add AI recommandation button (#20)
  frontend/public/gildong-home.png
  frontend/src/Router.tsx
  frontend/src/components/Footer.tsx
  frontend/src/screens/AI.tsx
  frontend/src/screens/Home.tsx
Labels: enhancement

#25 ✨ feat: Add comment link (#24)
  frontend/src/screens/FullTestSolve.tsx
  frontend/src/screens/RandomSolve.tsx
  frontend/src/screens/SpecificSolve.tsx
Labels: enhancement

#30 ✨ feat: AI recommendation based on last 100 problems (#29)
  frontend/src/screens/AI.tsx
Labels: enhancement

#31 🐛 fix: Fix jjim problem
  frontend/.firebase/hosting.YnVpbGQ.cache
  frontend/package-lock.json
  frontend/package.json
  frontend/src/screens/AI.tsx
  frontend/src/screens/FullTestSolve.tsx
  frontend/src/screens/Profile.tsx
  frontend/src/screens/RandomSolve.tsx
  frontend/src/screens/SpecificSolve.tsx
Labels: bug
